In [1]:
import numpy as np

In [2]:
list = [x for x in range(1,11)]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
my_array = np.array(list).reshape(10,1)
my_array

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
my_array.ndim
my_array.shape
# my_array.dtype

(10, 1)

In [11]:
np.ones((4,10), int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
np.zeros((10,10), int).reshape(5,20)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
np.random.seed(42)
# Generate random numbers
random_numbers = np.random.rand(5)
print(random_numbers)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [82]:
r=np.random.default_rng(42)
r.random(5)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735])

In [84]:
r.normal(50, 5 ,10)

array([43.48910247, 50.63920202, 48.41878704, 49.91599421, 45.73478036,
       54.39698987, 53.88895968, 50.33015349, 55.63620603, 52.33754671])

In [89]:
r.integers(1,101, size=(3,5))

array([[47, 86,  2, 76, 50],
       [72, 67, 44, 31, 63],
       [15, 59, 10, 65, 63]])

In [94]:
# my_arr = np.linspace(10,100, 10)
# my_arr
my_arr = np.arange(10,101, 10).reshape(5,2)
my_arr

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [107]:
rng = np.random.default_rng(2022)
random_arr = rng.random((3,3))
random_arr

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])