In [1]:
import numpy as np

In [3]:
integers = np.arange(10)
integers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
nrg = np.random.default_rng(2022)
random_array = nrg.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [13]:
random_array[0:2,:]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [21]:
random_array[:, 0].T

array([0.24742606, 0.06066207, 0.1108689 ])

In [23]:
random_array[2, 1]

0.04305584439252108

In [28]:
sales = [[0,5,155, 0,518], [0,1827, 616, 317,325]]
sales_arr = np.array(sales)
sales_arr

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [30]:
quantity = sales_arr[0,:]
quantity

array([  0,   5, 155,   0, 518])

In [31]:
price = sales_arr[1, :]
price

array([   0, 1827,  616,  317,  325])

In [32]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

In [35]:
rng = np.random.default_rng(2022)
p = (rng.random(11) * 10)
p

array([2.47426063, 0.92990062, 6.11763373, 0.60662074, 6.61033428,
       7.55157778, 1.10868901, 0.43055844, 4.14417474, 9.88629256,
       9.6919869 ])

In [67]:
prices = np.array([5.99,88.90, 22.33, 49.99,8.55,6.66])
total = prices + 5
total

array([10.99, 93.9 , 27.33, 54.99, 13.55, 11.66])

In [68]:
random_array[:2,]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [69]:
discount_pct = random_array[:2,:].reshape(6)
pct_owned = 1 - discount_pct
pct_owned

array([0.75257394, 0.90700994, 0.38823663, 0.93933793, 0.33896657,
       0.24484222])

In [70]:
pct_owned * total

array([ 8.27078756, 85.16823321, 10.61050701, 51.65419258,  4.59299705,
        2.85486031])

In [79]:
sales_arr = np.array([444,332,200,400, 0, 100, 0])
sales_arr

array([444, 332, 200, 400,   0, 100,   0])

In [80]:
sales_arr!= 0

array([ True,  True,  True,  True, False,  True, False])

In [81]:
sales_arr[sales_arr!=0]

array([444, 332, 200, 400, 100])